### ISSUE TITLE
Conversion of nested lists

### ISSUE THREAD

**Issue by philneff** [stencila/encoda#103]
Conversion of documents containing lists drops lower-level items in nested lists.

Tried to convert the following list:

```
1. Fruit
    - Apple
    - Orange
    - Banana
2. Dairy
    - Milk
    - Cheese
```

Tried various conversions: Markdown to Markdown; Docx to Markdown; Markdown to Docx. In all cases converted document only included top-level list items, e.g.:

```
1.  Fruit
2.  Dairy
```

**Comment by nokome** [comment]
Thanks for taking the time to submit this issue @philneff. I've created #105 to address it - hopefully we can resolve it fairly soon.

**Comment by alex-ketch** [comment]
Hi @philneff 👋
I wanted to let you know that with the [v0.51.0 release](https://github.com/stencila/encoda/releases/tag/v0.51.0) we have support for nested lists. There is a currently limitation when converting to/from Google Docs, but we plan on fixing that shortly as well.
I'll leave this issue open until we have full support, but we'd love it if you could give the new version a spin meanwhile :)

**Comment by nokome** [comment]
To avoid any confusion, the v0.51.0 release is of this repo, `encoda`. We are yet to update the `stencila` command line tool which Phil used at the UW eSciences workshop (still at [0.30.2](https://github.com/stencila/stencila/releases)) with this new version of `encoda`. Will ping back here when we do that.
