### ISSUE TITLE
Cannot find module './codecs/undefined' for Jupyter's "text/plain" output

### ISSUE THREAD

**Issue by rgaiacs** [stencila/encoda#143]
Some Jupyter output cells will be of the type `text/plain`, for example

```
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "2"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "1 + 1"
   ]
  }
```

`node dist/cli.js convert planets.ipynb planets.md` will raise

```
encoda WARN No codec was found for undefined

Error: Cannot find module './codecs/undefined'
```

if a `text/plain` cell output exists. https://github.com/stencila/encoda/blob/master/src/codecs/ipynb/index.ts#L424 need to be able to process the `text/plain` type.

**Note**: encoda generate the output file as expected.

**Comment by nokome** [comment]
Fixed by 6752abdcba8dea0c2f609ac4654ce49d51c5eb31
