### ISSUE TITLE
HTML: Encoding not escaping HTML

### ISSUE THREAD

**Issue by beneboy** [stencila/encoda#169]
To reproduce:

```
./encoda convert "{type: 'Paragraph', content: ['<em>','<strong>']}" --from json5 - --to html --standalone=false

<p><em><strong></p>
```

Expected output is 

```html
<p>&lt;em&gt;&lt;strong&gt;</p>
```

**Comment by nokome** [comment]
I suspect this is a simple fix on this line 

https://github.com/stencila/encoda/blob/4ed50b1c0fa0903c9dc3574ac11b24e99795bbf8/src/codecs/html/index.ts#L902-L904

probably just needs `escape(value)`. Should have a regression test added for in https://github.com/stencila/encoda/tree/master/src/__tests__/issues
