### ISSUE TITLE
MardownConverter: Add "success" message after converting plain Markdown

### ISSUE THREAD

**Issue by apawlik** [stencila/encoda#17]
At the moment there is no feedback whilst for example for `ipynb` conversion 
`Success: import from "hello-world.ipynb" to "hello-world.dar"`

**Comment by nokome** [comment]
At present, we are keeping the CLI in this repo very minimal and do not print a success message for any conversion. So I'll close this issue (which is really about inconsistency of success messages). If there is demand for this feedback, maybe we should add it to the `stencila` CLI.
