### ISSUE TITLE
Encoda fails conversion of Article example through Pandoc

### ISSUE THREAD

**Issue by beneboy** [stencila/encoda#178]
When trying to convert examples of `Article.md` in `schema` to targets that require Pandoc (e.g. JATS and OpenDocument [and possibly others but that's all I've tried]) I get the following failure:

```
  TypeError: Cannot read property 'map' of undefined
    at encodeBlocks (schema/node_modules/@stencila/encoda/dist/codecs/pandoc/index.js:332:18)
    at encodeNode (/schema/node_modules/@stencila/encoda/dist/codecs/pandoc/index.js:204:18)
    at Object.exports.encode (schema/node_modules/@stencila/encoda/dist/codecs/pandoc/index.js:64:34)
    at Object.exports.encode (schema/node_modules/@stencila/encoda/dist/codecs/jats/index.js:37:19)
    at Object.exports.encode (schema/node_modules/@stencila/encoda/dist/index.js:195:18)
```

Conversion of both the simple and complex examples in the `Article.md` file works to at least Markdown and HTML and I would guess others.

**Comment by nokome** [comment]
The "complex" example works for me, but the "simple" one fails because it has no `content` (and hence `content.map` fails). So changing the example to the following should fix it.

IMO, the `Article` schema should require `content` property (it currently only requires `title` and `authors`).

```json import=simple
{
  "type": "Article",
  "title": "Recherches sur les substances radioactives",
  "authors": [
    {
      "type": "Person",
      "honorificPrefix": "Dr",
      "givenNames": ["Marie", "Skłodowska"],
      "familyNames": ["Curie"],
      "honorificSuffix": "PhD"
    }
  ],
  "content": []
}
```

**Comment by beneboy** [comment]
How did you go about finding out the cause of this? I feel like I should have been able to figure that out but it would take me a long time – do you think it's just a matter of you being more familiar with the code?

Also shouldn't there be some error somewhere about the missing property?

**Comment by nokome** [comment]
> do you think it's just a matter of you being more familiar with the code?

Yeah, I think it's just that.

> Also shouldn't there be some error somewhere about the missing property?

Yeah, if `content` was a required property then an error would have been thrown at the point of ingestion, the code block with the `import` directive.

**Comment by nokome** [comment]
But also, at the point of encoding, Encoda should coerce the data so that the `encode` function just works (in this case, creating a `content: []`). We do some if that, but need to be more consistent.
