### ISSUE TITLE
QuoteBlock doesn't allow text-only content

### ISSUE THREAD

**Issue by beneboy** [stencila/encoda#190]
Attempting to convert a QuoteBlock to HTML

```
Error: coercing "{
  "type": "QuoteBlock",
  "content": [
    {
      "type": "Paragraph",
      "content": [
        "If you wish to make an apple pie from scratch, you must first invent the universe.",
        "by Carl Sagan - Cosmos"
      ]
    }
  ]
}": Error: /content/0 should have required property 'content' 
```

But it does have one?

Related to #96?

**Comment by nokome** [comment]
This issue was not related to `QuoteBlock` per se, but to how we were using Ajv for coercion and in particular the interaction of `useDefaults` and `removeAdditional` options and the `allOf` schema keyword.
