### ISSUE TITLE
HTML: Test encoding of structured data

### ISSUE THREAD

**Issue by nokome** [stencila/encoda#234]
Start using the [Google Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool) to test the machine readability of JSON-LD and Microdata that we encode into HTML. To do:

- [ ] Create some test fixtures of `Article`, `Datatable` etc (in JSON, to decouple from other codecs, but for convenience, perhaps generated from Markdown, JATS, CSV etc)
- [ ] Publish HTML generated for these fixtures to https://stencila.github.io/encoda/src/codecs/html/tests (add to docs build) so that they can be accessed from the GSDTT and we can put a link in the `html` codec's `README.md` like this one (which tests Encoda's own home page):

https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fstencila.github.io%2Fencoda

At the time of writing there is [no public API](https://support.google.com/webmasters/thread/2561708?hl=en) for the GSDTT. There is https://github.com/padosoft/laravel-google-structured-data-testing-tool but it is for PHP and uses an undocumented API. So, doing automated testing is likely to be more trouble than it is worth.

**Comment by nokome** [comment]
Just to document one of the issues here. Example HTML generated by 

```bash
./encoda convert https://elifesciences.org/articles/45187v2 temp.html
```

produces many errors on GSDTT, including two for each `itemprop=citation`

```html
<li id="bib55" itemscope="true" itemtype="https://schema.org/CreativeWork"
itemprop="citation"><span itemprop="title" itemscope="true">Fusion stage of HIV-1 entry
    depends on Virus-Induced cell surface exposure of phosphatidylserine</span>
<ol itemprop="authors" itemscope="true">
    <li itemscope="true" itemtype="https://schema.org/Person" itemprop="author"><span
        itemprop="familyName">Zaitseva</span><span itemprop="givenName">E</span></li>
    <li itemscope="true" itemtype="https://schema.org/Person" itemprop="author"><span
        itemprop="familyName">Zaitsev</span><span itemprop="givenName">E</span></li>
    <li itemscope="true" itemtype="https://schema.org/Person" itemprop="author"><span
        itemprop="familyName">Melikov</span><span itemprop="givenName">K</span></li>
    <li itemscope="true" itemtype="https://schema.org/Person" itemprop="author"><span
        itemprop="familyName">Arakelyan</span><span itemprop="givenName">A</span></li>
    <li itemscope="true" itemtype="https://schema.org/Person" itemprop="author"><span
        itemprop="familyName">Marin</span><span itemprop="givenName">M</span></li>
    <li itemscope="true" itemtype="https://schema.org/Person" itemprop="author"><span
        itemprop="familyName">Villasmil</span><span itemprop="givenName">R</span></li>
    <li itemscope="true" itemtype="https://schema.org/Person" itemprop="author"><span
        itemprop="familyName">Margolis</span><span itemprop="givenName">LB</span></li>
    <li itemscope="true" itemtype="https://schema.org/Person" itemprop="author"><span
        itemprop="familyName">Melikyan</span><span itemprop="givenName">GB</span></li>
    <li itemscope="true" itemtype="https://schema.org/Person" itemprop="author"><span
        itemprop="familyName">Chernomordik</span><span itemprop="givenName">LV</span></li>
</ol><time itemprop="datePublished" datetime="2017">2017</time>
</li>
```

![image](https://user-images.githubusercontent.com/1152336/64193805-a730f100-ced1-11e9-816d-d53284317a6b.png)

**Comment by nokome** [comment]
I've started on some fixes for this. Will push as a PR soon.

**Comment by nokome** [comment]
@alex-ketch discovered https://github.com/glitchdigital/structured-data-testing-tool which is specifically designed for this use case. Will change issue title accordingly.

**Comment by alex-ketch** [comment]
@nokome Having used [structured-data-testing-tool](https://github.com/glitchdigital/structured-data-testing-tool), I don't think it fulfils our needs just yet.
It detects presence of Schema.org MicroData attributes inside HTML documents, but does not validate them. There is an [issue documenting this here](https://github.com/glitchdigital/structured-data-testing-tool/issues/5#issuecomment-520591212).

We can explore writing a converter from schema JSON to [test format required by the tool](https://github.com/glitchdigital/structured-data-testing-tool#how-to-define-your-own-tests) if you'd like.

**Comment by nokome** [comment]
Thanks for looking into that. Let's leave it for now.

**Comment by nokome** [comment]
After spending quite a lot of time copying and pasting HTML into the GSDTT, I think that `structured-data-testing-tool` does provided value - if only about how well external tools are able to parse our Microdata (although it is able to do more). So I have added it as a `devDependency` 237ae92818e45a39a14917519b0fe8c9a615354c and will close this.
