### ISSUE TITLE
LaTeXConverter: tex_math_dollars, enable $ and $$

### ISSUE THREAD

**Issue by apawlik** [stencila/encoda#27]
As requested by [Jean](https://community.stenci.la/t/stencila-converter/147)

>One vote for `tex_math_dollars`, so that we can use `$` and `$$`, which is a [widely supported syntax](https://github.com/cben/mathdown/wiki/math-in-markdown#appendix-summary-table).

**Comment by nokome** [comment]
Just to note that LaTeX is supported in Word too https://www.nature.com/articles/d41586-019-01796-1. We'll look to add support for equations soon.
