### ISSUE TITLE
Checked ListItem nodes are not supported

### ISSUE THREAD

**Issue by alex-ketch** [stencila/encoda#306]
Todo list items are currently rendered as simple bullet lists, as can be seen from the markdown conversion screenshot below.

![Screen Shot 2019-10-09 at 22 54 48](https://user-images.githubusercontent.com/1646307/66535823-e95cdc00-eae8-11e9-92e3-82fa0e13674a.png)

The relevant piece of logic can be found at: https://github.com/stencila/encoda/blob/37bc41b65f6b83712708274142813b3f5ee39b13/src/codecs/html/index.ts#L1306-L1322

**Comment by nokome** [comment]
I was tidying up `encodeListItem` (which is actually where the issue resided) and so closed this issue at the same time.

![image](https://user-images.githubusercontent.com/1152336/76043171-93b72d80-5fbb-11ea-9818-28441d933b29.png)
