### ISSUE TITLE
hello-world.md converted to output.docx on MacOS High Sierra can't be opened on MS Word

### ISSUE THREAD

**Issue by lollopus** [stencila/encoda#33]
Downloaded the latest stencila CLI and attempted a convert to docx on the example hello-world.md file. The resulting file is rejected by MS Word for Mac 16.14.1: 
![error](https://user-images.githubusercontent.com/11914162/43674074-bfb8b12a-97c5-11e8-9bfc-849234a0745a.jpeg)

Importing in Pages also fails with an "Pages can't read the file" error.

Here is the actual file:
[output.docx](https://github.com/stencila/convert/files/2259308/output.docx)

**Comment by nokome** [comment]
I suspect this is no longer an issue (related to superseded approach to DOCX generation).

@alex-ketch Could you please confirm you can open a `.docx` created from `.md`, and if so, close this issue.

@all-contributors please add @lollopus for bug report

**Comment by alex-ketch** [comment]
@nokome I've been able to reproduce a conversion error from MD to DOCX when the markdown file contains native tables (HTML encoded tables don't seem to cause issues).
I'll investigate and report back with the exact cause.
