### ISSUE TITLE
xlsx to PDF conversion fails with 

### ISSUE THREAD

**Issue by apawlik** [stencila/encoda#34]
[Reported by burque505 - Winter Laite](https://community.stenci.la/t/missing-inserted-in-alignment-preamble-xlsx-to-pdf/206)

*Even a spreadsheet with only 6 cells, each containing only text, fails with the error mentioned. The json created, however, contains all the data.(...)
EDIT:
Code problem solved with bbcode tag (trying spoiler out also). By the way, I get a useable conversion by first converting xlxs -> md and then md -> pdf, but no charts so far.*

EDIT: problematic file attached

[TM.xlsx](https://github.com/stencila/convert/files/2560813/TM.xlsx)

**Comment by nokome** [comment]
Closing. The generated PDF FWIW: [test.pdf](https://github.com/stencila/encoda/files/3297549/test.pdf)
