### ISSUE TITLE
eLife: automatically fetch the most recent version

### ISSUE THREAD

**Issue by nokome** [stencila/encoda#368]
The [`elife` codec](https://github.com/stencila/encoda/blob/master/src/codecs/elife/index.ts) recognises a eLife article URL, parses out the article number and fetches the XML from the eLife Github repo. This is useful because it allows a user to copy and paste a eLife URL into the Hub and have it fetched automagically.

However, by default it will fetch the `v1` XML, not the most recent. This causes errors, because often the `v1` XML contains no body e.g

```bash
$ ./encoda convert https://elifesciences.org/articles/45562
⚠ WARN  encoda:elife Article 45562v1 has no body. You may wish to try another version.
⚠ WARN  encoda:jats Using default decoding for JATS element name: "article-title"
```

The user can explicitly add the version number to the URL e.g. `encoda convert https://elifesciences.org/articles/45562v3`. But that requires them to know the version.

It should be possible to query the Github API to find the most recent version for an article and fetch that.

**Comment by nokome** [comment]
Looks like the following API query gives what is needed:

https://api.github.com/search/code?q=%3Cbody%3E+repo:elifesciences/elife-article-xml+language:xml+filename:elife-49257

```json
{
  "total_count": 2,
  "incomplete_results": false,
  "items": [
    {
      "name": "elife-49257-v2.xml",
      "path": "articles/elife-49257-v2.xml",
      "sha": "466dc05b9bc519e69a6afb7096c18a6a7a12e107",
      "url": "https://api.github.com/repositories/47119121/contents/articles/elife-49257-v2.xml?ref=4bae4a84a7a87ab413d2ff19a0760741ca4b79b4",
      "git_url": "https://api.github.com/repositories/47119121/git/blobs/466dc05b9bc519e69a6afb7096c18a6a7a12e107",
      "html_url": "https://github.com/elifesciences/elife-article-xml/blob/4bae4a84a7a87ab413d2ff19a0760741ca4b79b4/articles/elife-49257-v2.xml",
      "repository": {
```

**Comment by giorgiosironi** [comment]
It's unclear how eLife articles IDs will eventually be extended over 99999, but the query should read:
```
filename:elife-49257-
```
to avoid matching 492571 or similar.

**Comment by giorgiosironi** [comment]
On the other hand, there may be easier ways to do this:
- check what is the newest version: `curl https://api.elifesciences.org/articles/30274/versions | jq '.versions[].version'`
- download the newest version JATS: `wget https://elifesciences.org/articles/30274.xml`
- download a specific version JATS: `wget https://elifesciences.org/articles/30274v1.xml`
