### ISSUE TITLE
JATS: Decoding of <article><front>

### ISSUE THREAD

**Issue by nokome** [stencila/encoda#395]
Currently, the `jats` codec only partially decodes the `<front>` element of a JATS article. This issue enumerates child elements of `<front>` that are currently not being decoded, focusing on eLife articles, e.g. [this test fixture](https://github.com/stencila/encoda/blob/87fec0da2627dbecafc3d381e59ea9163ce40453/src/codecs/jats/__fixtures__/elife-46793-v1/main.pretty.xml).  Suggest approaches to decoding, below. Relative priority (given by numbers :one: = lowest) somewhat arbitrary, but based on properties usually presented to reader.

### `journal-meta`

Currently, not being handled at all. Should decode to a `Periodical` that will be at the end of the `isPartOf` chain including `PublicationIssue` and `PublicationVolume` as needed:
- [x] :one: `journal-id` to `identifiers`
- [x] :two: `journal-title` to `title`
- [x] :two: `issn` to `issn`
- [x] :two: `publisher-name` to `publisher.name`

### `article-meta`

Only some of this element is being handled (e.g. `article-title`, `abstract`, `contrib[contrib-type="author"]`). Suggested handling of child elements:

- [x] :two: `article-id` and `elocation-id` elements to `article.identifiers`
- [x] :one: ~`article-categories subject` and~ `kwd` elements to `article.keywords`
- [x] :two: `contrib[contrib-type="editor"]` to `article.editors`
- [x] :one: `author-notes` to `article.meta['notes']`
- [x] :two: `pub-date[ date-type="publication"]` to `article.datePublished`
- [x] :two: `volume` to `article.isPartOf` (`PublicationVolume` linked to `Periodical`)
- [x] :one: `history date` elements to `article.meta['dateReceived']` etc
- [x] :one: `permissions license` to `article.licences`
- [x] :one: `funding-group award-group` to `article.fundedBy (Grant)` (see https://github.com/schemaorg/schemaorg/issues/2258)

@FAtherden-eLife Please leave a comment if there are important elements missing from this list or if the priority order needs refining. I'll be starting a PR for this soon.

**Comment by FAtherden-eLife** [comment]
Thanks @nokome,  can we bump this one up in proprity?
- [ ] :one: `article-id` and `elocation-id` elements to `article.identifiers`

I think our workflow will be simplified if this information is present in the content.

`journal-meta` is probably lowest priority (of everything), so unless that's already been done, we can probably ignore that for now.

Otherwise it looks good to me. 

I raised [an issue for appendices](https://github.com/stencila/encoda/issues/400), and was going to do the same for some other issues. Would you prefer me to add it all in one ticket, with what we consider to be priorities, similar to this one?

**Comment by nokome** [comment]
Thanks @FAtherden-eLife . I've bumped up that id item.

> Would you prefer me to add it all in one ticket, with what we consider to be priorities, similar to this one?

Generally it is better to have issues quite fine grained, representing discrete chunks of work that can be addressed in one PR. There is a "eLife meta issue" #398 to link to those more detailed issues (as a Collaborator on the repo, you should be able to edit my original comment there, I have already added your #400 there). But also, please feel free to lump issues if that is more convenient (as I did for this one)

**Comment by nokome** [comment]
Most of the issues above (the checked ones) have been addressed in #396 which is merged into master. Leaving this open until remaining items are dones.
