### ISSUE TITLE
Allow alternative ways to specify a theme

### ISSUE THREAD

**Issue by nokome** [stencila/encoda#397]
Currently, the options to the `encode` method must include a `theme` which is strongly typed to be one of the `ThemeName`s in Thema:

https://github.com/stencila/encoda/blob/f710c484c0f128ae3044d95cf1f1aae473f42c3d/src/codecs/types.ts#L1-L11

There are a number of issues related to this:

- `theme` is the only "option" that is not optional ; having it required creates situations where one must specify a theme even if it is not being used e.g.

https://github.com/stencila/encoda/blob/e57fcf75efa426dfdb86b1678a3c599a4e426463/src/codecs/njk/index.ts#L99-L106

- users wanting to use their own theme, not in the Thema repo, can't

Instead, the theme option could be:

```ts
theme?: string
```

with a convention like:

- if `theme` includes `://`  and `!isBundle` then use that as the URL
- if `isPath(theme)` and `isBundle` then read from that directory
- otherwise, assume the theme `string` is a Thema theme name.

See code around https://github.com/stencila/encoda/blob/a20804d11ca6c4368bb06486313bb4daf688bed0/src/codecs/html/index.ts#L510

**Comment by alex-ketch** [comment]
I agree with the overall goal of this, and have a few questions/suggestions.

Should we download and inline `theme` URL (`://`) contents if `isBundle` is set?

Another thought I had for the greatest flexibility in usage was to potentially split out the command into two flags, `--themeCSS` and `--themeJS` or something along those lines.
Usage would allow setting these flags multiple times, allowing combining as many stylesheets and JS files as needed.
My expectation being that each passed argument would be parsed according to the conventions you outlined above, in the order that they were passed in.

Some complications I anticipate could be around whether or not to set the `async` flag on the JS script tag, and whether to include it in the head or the end of the document (the end being the preferred initial place until we need to support other usage).
