### ISSUE TITLE
JATS: Decoding of inline and display formula

### ISSUE THREAD

**Issue by FAtherden-eLife** [stencila/encoda#403]
There appear to be some issues with the encoding of formula (in jats these are defined in `inline-formula` and `disp-formula`).

For example note in this article an example of each:
- [Inline formula (in the caption for Figure 1)](https://elifesciences.org/articles/52882#fig1)
- [display formula ](https://elifesciences.org/articles/52882#s4-3)

In the following JSON-LD file:
```
encoda convert https://elifesciences.org/articles/52882v2 elife-52882.jsonld
```

For both of these cases the formula seems to be placed after paragraph or position in the text, where they should be situated.

eLife would consider this issue to be high priority.

**Comment by nokome** [comment]
Thanks for pointing this out @FAtherden-eLife. Just to clarify - this is an issue with **de**coding - i.e. parsing the JATS.

There is a PR underway #383 which addresses `Math` nodes in general. So I will address this there. I have added a specific regression test for this article to the `jats` test suite.
