### ISSUE TITLE
JATS: Decoding of subjects

### ISSUE THREAD

**Issue by FAtherden-eLife** [stencila/encoda#468]
JATS has the elements `subj-group`, and `subject` which are used to define subjects related to an article.

eLife use this to define an article type, and subject area(s) related to an article.
```xml
<article-categories>
    <subj-group subj-group-type="display-channel">
        <subject>Tools and Resources</subject>
    </subj-group>
    <subj-group subj-group-type="heading">
        <subject>Neuroscience</subject>
    </subj-group>
    <subj-group subj-group-type="heading">
        <subject>Structural Biology and Molecular Biophysics</subject>
    </subj-group>
</article-categories>
```

For reference, eLife use `display-channel` for article-type and `heading` for subject area. (These are likely to change in the future and are not standard across all publishers where this value differs.)

These do not appear to be decoded. The following file:
```
encoda convert https://elifesciences.org/articles/53205 53205.jsonld
```

does not contain this information.

**Comment by nokome** [comment]
Closed by #666
