### ISSUE TITLE
Change binary name from stencila-convert to convert

### ISSUE THREAD

**Issue by alex-ketch** [stencila/encoda#51]
For ergonomics it would be nicer to have a more succinct name.

**Comment by nokome** [comment]
I agree but...

- `convert` clashes with the [commonly installed ImageMagick command of the same name](https://linux.die.net/man/1/convert) (and probably others!)
- I think we need to rename this tool (I am about to start a roadmap and suggest we go through a process as we did for https://github.com/stencila/dockter/issues/37)

**Comment by alex-ketch** [comment]
Potential name suggestion:

[**Janus**](https://en.wikipedia.org/wiki/Janus)
> Janus is the god of beginnings, gates, transitions, time, duality, doorways, passages, and endings. He is usually depicted as having two faces, since he looks to the future and to the past.

![](https://upload.wikimedia.org/wikipedia/commons/0/0c/Janus%2C_the_Roman_god_%281550%29.jpg)

**Comment by nokome** [comment]
Closing. We went with `encoda`.
