### ISSUE TITLE
HTML: Encode TableRows with 'rowType: header' inside <thead> and <th> elements

### ISSUE THREAD

**Issue by discodavey** [stencila/encoda#560]
It seems the tables in the articles are not showing the headers as table headers in the HTML. Please could this be fixed?

It is showing as this at the moment:

``` <tr><td></td></tr> ```

and should be like this:

``` <tr><th></th></tr> ```

**Comment by discodavey** [comment]
I have done an update and the table headers have not appeared. Is this down to the source or is this something missing?

<img width="675" alt="Screenshot 2020-05-22 at 09 14 45" src="https://user-images.githubusercontent.com/745794/82646563-b47f3e80-9c0c-11ea-8bfe-4199a57e223b.png">

**Comment by nokome** [comment]
Hi @discodavey. It seems that the HTML snippet that you shared was not generated using Encoda v0.93.11 (i.e. the latest release). This is the HTML I have (for the file `src/examples/articleReplication.html` in the Thema repo):

![image](https://user-images.githubusercontent.com/1152336/82652188-4ae54b80-9c71-11ea-870b-d08f750609a9.png)

Could you please try running the following again in the Thema repo:

```bash
git checkout update-encoda
npm install
npm run update:examples
npm run dev
```

If you don't get the above HTML then something really weird is going on.

**Comment by discodavey** [comment]
This branch works correctly now. Should this work like this on master?

**Comment by alex-ketch** [comment]
Thanks for confirming @discodavey, I'll merge https://github.com/stencila/thema/pull/181 into `master`

**Comment by discodavey** [comment]
Just to let you know that now the branch has been merged, my branch is now showing the table headers in the code.
