### ISSUE TITLE
HTML: Encode `Organization` `ContactPoints` in `Article#authors`

### ISSUE THREAD

**Issue by alex-ketch** [stencila/encoda#575]
Related to #550

> Encoding of `ContactPoints` will be added in a future PR
>
> _Originally posted by @alex-ketch in https://github.com/stencila/encoda/pull/573#issuecomment-635732094_

**Comment by nokome** [comment]
This has been done. In `encodeOrganization` function:

https://github.com/stencila/encoda/blob/862ce14d97ee16f70a1b391c3d12432d8013f2d5/src/codecs/html/index.ts#L1391-L1397
