### ISSUE TITLE
Improve speed of rPNG generation

### ISSUE THREAD

**Issue by nokome** [stencila/encoda#61]
Currently rPNG generation is quite slow. This is not a huge issue but could become one with documents that contain many reproducible elements (e.g. lots of within text code expressions providing analysis results). The `pandoc.test.ts` which involves generation of six rPNGs is noticebly slow  https://travis-ci.org/stencila/convert/jobs/532638335#L144

### A little test

Here are Markdown document with some non-textual nodes:

```markdown
A !number(1) and a !boolean(true) and an !array(1,2,3,4,5) and an !object("a":1, "b":2)
```

When converted to Word `bin/stencila-convert temp.md ./temp.docx` the "non-textual" nodes get converted to rPNGs:

![image](https://user-images.githubusercontent.com/1152336/57753058-2c37a500-773f-11e9-9c88-56874b67a161.png)

Which takes an average of 3.5s (and shows spike in network traffic associated with fetching `highlight.js` presumably): 

```bash
bash -c "time for i in {1..10}; do bin/stencila-convert temp.md ./temp.docx; done"

real    0m35.710s
user    0m21.296s
sys     0m4.856s
```

If you remove the exclamation marks (i.e. remove the Commonmark inline extension syntax):

```markdown
A number(1) and a boolean(true) and an array(1,2,3,4,5) and an object("a":1, "b":2)
```

Then there are no rPNGs and the time drops to 1.1 seconds (only slightly above the base startup time, https://github.com/stencila/convert/issues/60).

```bash
bash -c "time for i in {1..10}; do bin/stencila-convert temp.md ./temp.docx; done"

real    0m11.092s
user    0m13.652s
sys     0m1.008s
```

### Potential solution

It seems that the first approach would to lazy, and only once, initialise a rendering page. That is, do this https://github.com/stencila/convert/blob/99975bbdcd3526d98041d98bf0f098b867d770d4/src/rpng.ts#L208-L216 outside of the `unparse` function, and only as needed.

**Comment by alex-ketch** [comment]
Re. network dependency, I can investigate bundling Highlight.js as part of the package and referencing the JS that way. Without a build tool inclusion of CSS is a little tricker, since TS compiler doesn't support it natively, so we'd have to either manually bundle the CSS during build, copy-paste the CSS as a string, or introduce a build tool into the mix.
The latter option does open up further optimizations like tree-shaking mentioned in #60 though.
