### ISSUE TITLE
unable to convert .docx to .ipynb

### ISSUE THREAD

**Issue by kayarre** [stencila/encoda#668]
Unsure how to debug the error:
```
 ERROR encoda Cannot read property 'content' of undefined
```
I am trying to convert this available resource: https://github.com/NCAR/CfRadial/tree/master/docs
e.g.
./encoda convert ~/Downloads/CfRadialDoc-v2.1-20190901.docx ~/Downloads/CfRadialDoc-v2.1-20190901.ipynb

[2020-09-03T16_51_43_440Z-debug.log](https://github.com/stencila/encoda/files/5170148/2020-09-03T16_51_43_440Z-debug.log)

**Comment by nokome** [comment]
Thanks for the detailed bug report @kayarre. I can confirm that I get the same error on Ubuntu 16.04 (:scream: yes, I need to get around to upgrading!). It appears to be an issue decoding this `.docx` because attempting to convert `.json` gives the same error.

I'm looking into it now.
