### ISSUE TITLE
MD: programming language is incorrectly decoded

### ISSUE THREAD

**Issue by alex-ketch** [stencila/encoda#725]
Given the following RMD:

````rmd
# Test

```{python fig2}

# R code here

```
````

The programming language is captured as `"programmingLanguage": "{python",`

**Comment by alex-ketch** [comment]
@nokome This seems to be happening in the `md` codec's handling of `decodeCodeblock`, not `xmd` side.

**Comment by nokome** [comment]
But the `XmdCodec` should have "unbraced" it here: https://github.com/stencila/encoda/blob/231933e536b5295f7f2d724e1cb53126b0f762ed/src/codecs/xmd/index.ts#L173

Anyway, I'll create an issue test and see.

**Comment by nokome** [comment]
This was related to #717 and has been fixed. See PR #726
