### ISSUE TITLE
github website URL is 404

### ISSUE THREAD

**Issue by IndrajeetPatil** [stencila/encoda#809]
<img width="360" alt="Screenshot 2021-01-21 at 17 07 45" src="https://user-images.githubusercontent.com/11330453/105377562-3ba50c00-5c0b-11eb-96e1-642b6865e66e.png">

**Comment by alex-ketch** [comment]
Thanks for spotting this @IndrajeetPatil! I've updated the link to point to the correct address (https://stencila.github.io/encoda/api/).
Having said that, the website is simply a stylized presentation of the README files from this project at the moment, but we do have plans for a more content rich site in the future.
