### ISSUE TITLE
Trying to fetch upscaled images from eLife article throws an error

### ISSUE THREAD

**Issue by alex-ketch** [stencila/encoda#826]
When converting an eLife source we fetch the JATS XML from the eLife GitHub repository and download the corresponding media assets from a separate image hosting server.
The image server is able to dynamically resize the requested assets based on the URL, which we have currently configured to request images at 600px width.

https://github.com/stencila/encoda/blob/8242ac021eeec3adc271f7c060f36ecf7887c6ed/src/codecs/elife/index.ts#L88

This approach however fails to convert if the source image is below 600px width, such as a figure found in [this article](https://elifesciences.org/articles/61277).

To test run:

```sh
encoda convert https://elifesciences.org/articles/61277 ./testArticle.html
```

**Comment by nokome** [comment]
Thanks @alex-ketch. Note issue #379 which proposes a simpler approach to fetching eLife XML. This simpler approach has been implemented as a job on the hub: https://github.com/stencila/hub/blob/master/worker/jobs/pull/elife.py. So any fix also needs to be implemented there, in Python.

Going forward, it would be good not to have multiple implementations of the same functionality to maintain. Being able to easily test "jobs" like you have here on the CLI is very useful, and ideally the hub would just shell out to Encoda or some other CLI tool to do these "pull" jobs (as we do for `convert` jobs). This fits in with the notion of the Hub being "just an online deployment" of our other tools. I've been doing some refactoring of APIs and CLIs lately and reconsidering where various functionality should live. So we revisit this then.

**Comment by alex-ketch** [comment]
Closed by https://github.com/stencila/encoda/pull/827
