### ISSUE TITLE
md to docx: extra "Untitled" page generated

### ISSUE THREAD

**Issue by jwijay** [stencila/encoda#92]
An extra page is generated, when converting from `md` to `docx`.
Tested this conversion with the following `md` file: https://github.com/datacarpentry/R-ecology-lesson/blob/master/README.md

`npx ts-node --files src/cli convert examples/R-ecology-lesson/README.md ./examples/output/README.docx`

Output README.docx:
![Screenshot 2019-06-05 11 45 13](https://user-images.githubusercontent.com/10161095/58981787-ebeca500-8787-11e9-9852-79117bff40e0.png)

Also tested with a simple `md` file (with the following contents), and the output docx has the same extra page:
```
# Data carpentry: R for data analysis and visualization of Ecological Data

This is an introduction to R designed for participants with no programming
experience. These lessons can be taught in 3/4 of a day (approximately 6 hours). They start
with some basic information about syntax for the R programming language, the
RStudio interface, and move through to specific programming tasks, such as
importing CSV files, the structure of data frame objects in R, dealing with
categorical variables (i.e. factors), basic data manipulation (adding/removing
rows and columns), and finishing with calculating summary statistics and a brief
introduction to plotting. There is also a lesson on how to use databases from R that is intended to be taught after the SQL lesson, and ideally at the end of a Data Carpentry workshop.
```

**Comment by rgaiacs** [comment]
@jwijay Thanks for the issue. I would like to provide a bit of details to what is happening.

encoda expect that Markdown documents are going to have a YAML header, e.g.

```
----
title: Data carpentry: R for data analysis and visualization of Ecological Data
----

This is an introduction to R designed for participants with no programming experience.
```

If you don't provide the YAML header, you will get the "Untitled" heading. By changing the first few lines of [your document](https://github.com/datacarpentry/R-ecology-lesson/blob/master/README.md) to

```
---
title: "Data carpentry: R for data analysis and visualization of Ecological Data"
---

[![Build Status](https://travis-ci.org/datacarpentry/R-ecology-lesson.svg?branch=master)](https://travis-ci.org/datacarpentry/R-ecology-lesson)
[![Create a Slack Account with us](https://img.shields.io/badge/Create_Slack_Account-The_Carpentries-071159.svg)](https://swc-slack-invite.herokuapp.com/)
[![Slack Status](https://img.shields.io/badge/Slack_Channel-DC_Ecology_R-E01563.svg)](https://swcarpentry.slack.com/messages/C9X9EC405)

This is an introduction to R designed for participants with no programming
experience.
```

you will get

![data-carpentry](https://user-images.githubusercontent.com/1506457/60482207-7beb1500-9c88-11e9-9e29-173a707e76a5.png)

I created https://github.com/stencila/encoda/issues/147 as a duplication of this issue.
